/**
 * Seed Data for CMS MCP Server
 * Matches bankingcoredemo data structure
 * 40 INDIVIDUAL customers + 10 BUSINESS customers
 */

const { v4: uuidv4 } = require('uuid');

// Helper to generate dates
const daysAgo = (days) => new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
const yearsAgo = (years) => new Date(Date.now() - years * 365 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];

/**
 * 40 INDIVIDUAL Customers
 * Matches bankingcoredemo profiles with realistic financial data
 */
const individualCustomers = [
  {
    customer_id: uuidv4(),
    customer_type: 'INDIVIDUAL',
    first_name: 'Sarah',
    last_name: 'Miller',
    email: 'sarah.miller0@example.com',
    phone: '+1-713-555-0101',
    date_of_birth: yearsAgo(35),
    address_line1: '123 Main Street',
    address_line2: 'Apt 4B',
    city: 'Houston',
    state: 'TX',
    postal_code: '77001',
    country: 'USA',
    kyc_status: 'APPROVED',
    risk_rating: 'HIGH',
    annual_income: 250000,
    employment_status: 'EMPLOYED',
    occupation: 'Senior Engineer',
  },
  {
    customer_id: uuidv4(),
    customer_type: 'INDIVIDUAL',
    first_name: 'Lisa',
    last_name: 'Williams',
    email: 'lisa.williams1@example.com',
    phone: '+1-214-555-0102',
    date_of_birth: yearsAgo(29),
    address_line1: '456 Oak Avenue',
    city: 'Dallas',
    state: 'TX',
    postal_code: '75201',
    country: 'USA',
    kyc_status: 'APPROVED',
    risk_rating: 'LOW',
    annual_income: 85000,
    employment_status: 'EMPLOYED',
    occupation: 'Marketing Manager',
  },
  {
    customer_id: uuidv4(),
    customer_type: 'INDIVIDUAL',
    first_name: 'James',
    last_name: 'Williams',
    email: 'james.williams2@example.com',
    phone: '+1-210-555-0103',
    date_of_birth: yearsAgo(42),
    address_line1: '789 River Road',
    city: 'San Antonio',
    state: 'TX',
    postal_code: '78201',
    country: 'USA',
    kyc_status: 'APPROVED',
    risk_rating: 'LOW',
    annual_income: 95000,
    employment_status: 'EMPLOYED',
    occupation: 'Sales Director',
  },
  {
    customer_id: uuidv4(),
    customer_type: 'INDIVIDUAL',
    first_name: 'Lisa',
    last_name: 'Brown',
    email: 'lisa.brown3@example.com',
    phone: '+1-214-555-0104',
    date_of_birth: yearsAgo(38),
    address_line1: '321 Elm Street',
    city: 'Dallas',
    state: 'TX',
    postal_code: '75202',
    country: 'USA',
    kyc_status: 'APPROVED',
    risk_rating: 'HIGH',
    annual_income: 180000,
    employment_status: 'SELF_EMPLOYED',
    occupation: 'Business Consultant',
  },
  {
    customer_id: uuidv4(),
    customer_type: 'INDIVIDUAL',
    first_name: 'Mary',
    last_name: 'Davis',
    email: 'mary.davis4@example.com',
    phone: '+1-312-555-0105',
    date_of_birth: yearsAgo(31),
    address_line1: '555 Lake Shore Drive',
    city: 'Chicago',
    state: 'IL',
    postal_code: '60601',
    country: 'USA',
    kyc_status: 'APPROVED',
    risk_rating: 'LOW',
    annual_income: 72000,
    employment_status: 'EMPLOYED',
    occupation: 'Teacher',
  },
  {
    customer_id: uuidv4(),
    customer_type: 'INDIVIDUAL',
    first_name: 'Michael',
    last_name: 'Martinez',
    email: 'michael.martinez6@example.com',
    phone: '+1-619-555-0106',
    date_of_birth: yearsAgo(45),
    address_line1: '888 Harbor View',
    city: 'San Diego',
    state: 'CA',
    postal_code: '92101',
    country: 'USA',
    kyc_status: 'APPROVED',
    risk_rating: 'LOW',
    annual_income: 110000,
    employment_status: 'EMPLOYED',
    occupation: 'Software Engineer',
  },
  {
    customer_id: uuidv4(),
    customer_type: 'INDIVIDUAL',
    first_name: 'James',
    last_name: 'Davis',
    email: 'james.davis7@example.com',
    phone: '+1-214-555-0107',
    date_of_birth: yearsAgo(33),
    address_line1: '999 Cedar Lane',
    city: 'Dallas',
    state: 'TX',
    postal_code: '75203',
    country: 'USA',
    kyc_status: 'APPROVED',
    risk_rating: 'LOW',
    annual_income: 88000,
    employment_status: 'EMPLOYED',
    occupation: 'Financial Analyst',
  },
  {
    customer_id: uuidv4(),
    customer_type: 'INDIVIDUAL',
    first_name: 'Robert',
    last_name: 'Jones',
    email: 'robert.jones8@example.com',
    phone: '+1-213-555-0108',
    date_of_birth: yearsAgo(50),
    address_line1: '111 Sunset Boulevard',
    city: 'Los Angeles',
    state: 'CA',
    postal_code: '90001',
    country: 'USA',
    kyc_status: 'APPROVED',
    risk_rating: 'LOW',
    annual_income: 125000,
    employment_status: 'EMPLOYED',
    occupation: 'Project Manager',
  },
  {
    customer_id: uuidv4(),
    customer_type: 'INDIVIDUAL',
    first_name: 'Michael',
    last_name: 'Johnson',
    email: 'michael.johnson9@example.com',
    phone: '+1-214-555-0109',
    date_of_birth: yearsAgo(27),
    address_line1: '222 Pine Street',
    city: 'Dallas',
    state: 'TX',
    postal_code: '75204',
    country: 'USA',
    kyc_status: 'APPROVED',
    risk_rating: 'LOW',
    annual_income: 65000,
    employment_status: 'EMPLOYED',
    occupation: 'Data Analyst',
  },
  {
    customer_id: uuidv4(),
    customer_type: 'INDIVIDUAL',
    first_name: 'Michael',
    last_name: 'Jones',
    email: 'michael.jones10@example.com',
    phone: '+1-215-555-0110',
    date_of_birth: yearsAgo(24),
    address_line1: '333 Market Street',
    city: 'Philadelphia',
    state: 'PA',
    postal_code: '19101',
    country: 'USA',
    kyc_status: 'PENDING',
    risk_rating: 'HIGH',
    annual_income: 45000,
    employment_status: 'EMPLOYED',
    occupation: 'Junior Developer',
  },
  // Add 30 more INDIVIDUAL customers
  ...Array.from({ length: 30 }, (_, i) => {
    const firstNames = ['John', 'Emily', 'David', 'Jennifer', 'William', 'Jessica', 'Daniel', 'Amanda', 'Christopher', 'Ashley'];
    const lastNames = ['Smith', 'Johnson', 'Anderson', 'Taylor', 'Thomas', 'Moore', 'Jackson', 'Martin', 'Lee', 'White'];
    const cities = ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'Austin'];
    const states = ['NY', 'CA', 'IL', 'TX', 'AZ', 'PA', 'TX', 'CA', 'TX', 'TX'];
    const occupations = ['Engineer', 'Manager', 'Analyst', 'Designer', 'Developer', 'Consultant', 'Administrator', 'Specialist', 'Coordinator', 'Associate'];
    
    const idx = (i + 11) % 10;
    const income = 50000 + Math.floor(Math.random() * 150000);
    const kycStatuses = ['APPROVED', 'APPROVED', 'APPROVED', 'APPROVED', 'PENDING'];
    const riskRatings = ['LOW', 'LOW', 'LOW', 'MEDIUM', 'HIGH'];
    
    return {
      customer_id: uuidv4(),
      customer_type: 'INDIVIDUAL',
      first_name: firstNames[idx],
      last_name: lastNames[idx],
      email: `${firstNames[idx].toLowerCase()}.${lastNames[idx].toLowerCase()}${i + 11}@example.com`,
      phone: `+1-${200 + idx}${200 + i}-555-0${111 + i}`,
      date_of_birth: yearsAgo(25 + Math.floor(Math.random() * 30)),
      address_line1: `${100 * (i + 4)} ${['Main', 'Oak', 'Elm', 'Pine', 'Maple'][idx % 5]} Street`,
      city: cities[idx],
      state: states[idx],
      postal_code: `${10000 + i * 1000}`,
      country: 'USA',
      kyc_status: kycStatuses[i % 5],
      risk_rating: riskRatings[i % 5],
      annual_income: income,
      employment_status: Math.random() > 0.9 ? 'SELF_EMPLOYED' : 'EMPLOYED',
      occupation: occupations[idx],
    };
  }),
];

/**
 * 10 BUSINESS Customers
 * Various business types with higher income and credit needs
 */
const businessCustomers = [
  {
    customer_id: uuidv4(),
    customer_type: 'BUSINESS',
    business_name: 'Cloud Systems Inc',
    email: 'finance@cloudsystems.com',
    phone: '+1-415-555-0201',
    ein: '12-3456789',
    address_line1: '100 Technology Drive',
    city: 'San Francisco',
    state: 'CA',
    postal_code: '94102',
    country: 'USA',
    kyc_status: 'APPROVED',
    risk_rating: 'MEDIUM',
    annual_income: 5000000,
    employment_status: 'BUSINESS',
    occupation: 'Technology Services',
  },
  {
    customer_id: uuidv4(),
    customer_type: 'BUSINESS',
    business_name: 'Tech Solutions LLC',
    email: 'accounting@techsolutions.com',
    phone: '+1-512-555-0202',
    ein: '23-4567890',
    address_line1: '200 Innovation Plaza',
    city: 'Austin',
    state: 'TX',
    postal_code: '78701',
    country: 'USA',
    kyc_status: 'APPROVED',
    risk_rating: 'LOW',
    annual_income: 3500000,
    employment_status: 'BUSINESS',
    occupation: 'IT Consulting',
  },
  {
    customer_id: uuidv4(),
    customer_type: 'BUSINESS',
    business_name: 'Innovation Labs Corp',
    email: 'finance@innovationlabs.com',
    phone: '+1-617-555-0203',
    ein: '34-5678901',
    address_line1: '300 Research Way',
    city: 'Boston',
    state: 'MA',
    postal_code: '02101',
    country: 'USA',
    kyc_status: 'APPROVED',
    risk_rating: 'HIGH',
    annual_income: 8000000,
    employment_status: 'BUSINESS',
    occupation: 'R&D and Innovation',
  },
  {
    customer_id: uuidv4(),
    customer_type: 'BUSINESS',
    business_name: 'Digital Services Corp',
    email: 'billing@digitalservices.com',
    phone: '+1-206-555-0204',
    ein: '45-6789012',
    address_line1: '400 Cloud Avenue',
    city: 'Seattle',
    state: 'WA',
    postal_code: '98101',
    country: 'USA',
    kyc_status: 'APPROVED',
    risk_rating: 'MEDIUM',
    annual_income: 4200000,
    employment_status: 'BUSINESS',
    occupation: 'Digital Transformation',
  },
  {
    customer_id: uuidv4(),
    customer_type: 'BUSINESS',
    business_name: 'Global Enterprises Ltd',
    email: 'finance@globalent.com',
    phone: '+1-312-555-0205',
    ein: '56-7890123',
    address_line1: '500 Commerce Street',
    city: 'Chicago',
    state: 'IL',
    postal_code: '60602',
    country: 'USA',
    kyc_status: 'APPROVED',
    risk_rating: 'LOW',
    annual_income: 6500000,
    employment_status: 'BUSINESS',
    occupation: 'Import/Export',
  },
  {
    customer_id: uuidv4(),
    customer_type: 'BUSINESS',
    business_name: 'Retail Partners Group',
    email: 'accounts@retailpartners.com',
    phone: '+1-404-555-0206',
    ein: '67-8901234',
    address_line1: '600 Peachtree Road',
    city: 'Atlanta',
    state: 'GA',
    postal_code: '30301',
    country: 'USA',
    kyc_status: 'APPROVED',
    risk_rating: 'MEDIUM',
    annual_income: 2800000,
    employment_status: 'BUSINESS',
    occupation: 'Retail Management',
  },
  {
    customer_id: uuidv4(),
    customer_type: 'BUSINESS',
    business_name: 'Manufacturing Solutions Inc',
    email: 'finance@mfgsolutions.com',
    phone: '+1-313-555-0207',
    ein: '78-9012345',
    address_line1: '700 Industrial Parkway',
    city: 'Detroit',
    state: 'MI',
    postal_code: '48201',
    country: 'USA',
    kyc_status: 'APPROVED',
    risk_rating: 'LOW',
    annual_income: 4800000,
    employment_status: 'BUSINESS',
    occupation: 'Manufacturing',
  },
  {
    customer_id: uuidv4(),
    customer_type: 'BUSINESS',
    business_name: 'Financial Advisors LLC',
    email: 'operations@finadvisors.com',
    phone: '+1-212-555-0208',
    ein: '89-0123456',
    address_line1: '800 Wall Street',
    city: 'New York',
    state: 'NY',
    postal_code: '10005',
    country: 'USA',
    kyc_status: 'APPROVED',
    risk_rating: 'HIGH',
    annual_income: 12000000,
    employment_status: 'BUSINESS',
    occupation: 'Financial Services',
  },
  {
    customer_id: uuidv4(),
    customer_type: 'BUSINESS',
    business_name: 'Healthcare Systems Group',
    email: 'billing@healthcaresys.com',
    phone: '+1-713-555-0209',
    ein: '90-1234567',
    address_line1: '900 Medical Center Drive',
    city: 'Houston',
    state: 'TX',
    postal_code: '77002',
    country: 'USA',
    kyc_status: 'APPROVED',
    risk_rating: 'MEDIUM',
    annual_income: 7500000,
    employment_status: 'BUSINESS',
    occupation: 'Healthcare IT',
  },
  {
    customer_id: uuidv4(),
    customer_type: 'BUSINESS',
    business_name: 'Startup Ventures Inc',
    email: 'admin@startupventures.com',
    phone: '+1-650-555-0210',
    ein: '01-2345678',
    address_line1: '1000 Sand Hill Road',
    city: 'Palo Alto',
    state: 'CA',
    postal_code: '94301',
    country: 'USA',
    kyc_status: 'PENDING',
    risk_rating: 'HIGH',
    annual_income: 1500000,
    employment_status: 'BUSINESS',
    occupation: 'Venture Capital',
  },
];

// Combine all customers
const allCustomers = [...individualCustomers, ...businessCustomers];

// Add created_at and updated_at timestamps
allCustomers.forEach(customer => {
  customer.created_at = daysAgo(Math.floor(Math.random() * 365));
  customer.updated_at = daysAgo(Math.floor(Math.random() * 30));
});

module.exports = {
  customers: allCustomers,
  individualCustomers,
  businessCustomers,
};

